export const ROUTES = {
  home: '/',
  about: '/about',
  instruments: '/trading-instruments',
  instrument: (slug: string) => `/trading-instruments/${slug}`,
  platforms: '/platforms',
  accountTypes: '/account-types',
  conditions: '/trading-conditions',
  safety: '/safety-of-funds',
  education: '/education',
  article: (slug: string) => `/education/${slug}`,
  faq: '/faq',
  contact: '/contact',
  legal: {
    terms: '/legal/terms',
    privacy: '/legal/privacy',
    riskDisclosure: '/legal/risk-disclosure',
    amlKyc: '/legal/aml-kyc',
  },
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verify: '/auth/verify',
    resetPassword: '/auth/reset-password',
    callback: '/auth/callback',
  },
  portal: {
    dashboard: '/portal/dashboard',
    portfolio: '/portal/portfolio',
    aiTrading: '/portal/ai-trading',
    deposit: '/portal/deposit',
    withdrawal: '/portal/withdrawal',
    tradeHistory: '/portal/trade-history',
    kyc: '/portal/kyc',
    support: '/portal/support',
    ticket: (id: string) => `/portal/support/${id}`,
    settings: '/portal/settings',
  },
} as const
